routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::resource('collections', 'CollectionController');
Route::get('collections/{collection_id}/create_series', 'SeriesController@create')->name('series-create');
Route::get('collections/{collection_id}/permissions', 'CollectionPermissionController@index' )->name('collection_permission');
Route::post('collections/{collection_id}/permissions/update', 'CollectionPermissionController@update' )->name('update_permissions');

Route::resource('series', 'SeriesController');
Route::get('series/{series_id}/create_document', 'DocumentController@create')->name('document-create');

Route::resource('documents', 'DocumentController');
Route::get('documents/{document_id}/pdf', 'DocumentController@pdf')->name('document-pdf');
Route::get('documents/{document_id}/digitise', 'DocumentController@createDigitisedText' )->name('create-digitised');
Route::post('documents/{document_id}/digitise/store', 'DocumentController@storeDigitisedText' )->name('store-digitised');

Route::get('documents/{document_id}/tag/add/{user_id}', 'DocumentController@addTags' )->name('add-tags');
Route::get('documents/{document_id}/tag/view/{user_id}', 'DocumentController@viewTags' )->name('view-tags');
Route::get('documents/{document_id}/tag/edit/{user_id}/{tag_id}', 'DocumentController@editTags' )->name('edit-tag');
Route::post('documents/{document_id}/tag/store/{user_id}', 'DocumentController@storeTags' )->name('store-tags');

Route::get('documents/{document_id}/tag/add/{user_id}', 'DocumentController@addTags' )->name('add-tags');
Route::get('documents/{document_id}/tag/view/{user_id}', 'DocumentController@viewTags' )->name('view-tags');
Route::get('documents/{document_id}/tag/edit/{user_id}/{tag_id}', 'DocumentController@editTags' )->name('edit-tag');
Route::post('documents/{document_id}/tag/store/{user_id}', 'DocumentController@storeTags' )->name('store-tags');

Route::resource('tag', 'TagController');
Route::get('documents/{document_id}/tag/view/{user_id}', 'TagController@viewTags' )->name('view-tags');
Route::get('documents/{document_id}/tag/edit/{user_id}/{tag_id}', 'TagController@editTags' )->name('edit-tags');
Route::get('documents/{document_id}/tag/add/{user_id}', 'TagController@addTags' )->name('add-tags');
Route::post('documents/{document_id}/tag/store/{user_id}', 'TagController@storeTags' )->name('store-tags');
Route::get('documents/{document_id}/tag/create', 'TagController@createNewTag' )->name('create-tag');

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\CollectionTag;
use App\ComboBoxOption;
use App\Document;
use App\DocumentTag;
use App\User;
use DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

class TagController extends Controller
{
    /**
     * Show the list of Collection Tags the user has already created
     *
     * @param
     * @param
     * @throws
     * @return
     */
    public function viewTags($document_id, $user_id)
    {
        //retreives the document from DB with given id
        $document = Document::findOrFail($document_id);
        $user = User::findOrFail($user_id);
        //check if user can view tag
        $this->authorize('view', $document);


        $collection = $document->getCollection();

        $userDefinedCollectionTags = CollectionTag::getUserDefinedTags($user->id, $collection->id);

        $categories = $userDefinedCollectionTags->unique('category');

        $comboOptions = ComboBoxOption::where('collection_id', $collection->id)->where('owner_id', $user->id);

        return view('/tags/view', array('document' => $document, 'userDefinedCollectionTags' => $userDefinedCollectionTags,
            'comboOptions' => $comboOptions, 'categories' => $categories,'user'=> $user->id));
    }

    /**
     * Displays a view form to allow the user to create a custom Collection Tag
     *
     * @param
     * @return
     */
    public function createNewTag($id)
    {

        // Find document
        $document = Document::find($id);

        // Get the types
        $types = CollectionTag::getTypes();

        // JS requires "combo", but combo options are done in the DB
        // as 'string' types with ComboBoxOption entries
        $types[] = 'combo';

        return view('/tags/create', ['document' => $document, 'types' => $types]);

    }

    /**
     * Thit function stores a custom Collection tag created by the user in the DB.
     * The stored tag will be available to users when assigning doucment tags to a document
     *
     * @param
     * @return
     */
    public function store(Request $request)
    {
        //find document
        $document = Document::findOrFail($request->input('document_id'));
        $collection = $document->getCollection();

        $user = User::findOrFail($request->input('user_id'));

        if ($request->input('type') == "combo") {
            $this->validate($request, [
                'name' => 'required|unique:collection_tags,name',
                'type' => 'required',
                'category' => 'required',
                'options.*' => 'required|unique:document_tags_combo_options,value'
            ]);
        } else {
            $this->validate($request, [
                'name' => 'required|unique:collection_tags,name',
                'type' => 'required',
                'category' => 'required',
            ]);
        }

        //create array of data for collection tag
        $col_tag_data = [
            'collection_id' => $collection->id,
            'owner_id' => $user->id,
            'name' => $request->input('name'),
            'type' => $request->input('type'),
            'category' => $request->input('category')
        ];

        if ($request->input('type') == "combo") {

            $col_tag_data['type'] = "string";
        }

        //create a collection tag using the array
        //also get collectionTag obj
        $collection_tag = CollectionTag::create($col_tag_data);

        if ($request->input('type') == "combo") {

            foreach ($request->input('options') as $comboOption) {

                $combo_option_data = [
                    'tag_id' => $collection_tag->id,
                    'value' => $comboOption,
                ];

                //create a combo option row using the POST data
                ComboBoxOption::create($combo_option_data);

            }
        }

        return redirect()->route('add-tags', ['document' => $document->id, 'user_id' => $user->id]);
    }

    /**
     * Displays a view form to allow the user to edit a custom Collection Tag
     *
     * @param
     * @param
     * @param
     * @throws
     * @return
     *
     */
    public function editTags(Request $request, $document_id, $user_id, $tag_id)
    {
        //find document
        //retreives the document from DB with given id
        $document = Document::findOrFail($document_id);
        $user = User::findOrFail($user_id);
        //check if user can view tag
        $this->authorize('update', $document);

        // Get the types
        $types = CollectionTag::getTypes();

        // JS requires "combo", but combo options are done in the DB
        // as 'string' types with ComboBoxOption entries
        $types[] = 'combo';

        $collection = $document->getCollection();

        $userDefinedCollectionTags = CollectionTag::getUserDefinedTags($user->id, $collection->id);

        $tag = $userDefinedCollectionTags->where('id', '=', $tag_id)->first();

        $comboOptions = ComboBoxOption::where('collection_id', $collection->id)->where('owner_id', $user->id);

        return view('/tags/edit', array('document' => $document, 'tag' => $tag,
            'comboOptions' => $comboOptions,  'types' => $types));

    }


    /**
     * Edits the current Collection Tag defined by the user and updates in database
     *
     * @param
     * @param
     * @return
     */
    public function update(Request $request, $tag_id)
    {
        //find document
        $document = Document::findOrFail($request->input('document_id'));
        $collection = $document->getCollection();
        $tag = CollectionTag::findOrFail($tag_id);
        $user = User::findOrFail($request->input('user_id'));

//        $combo_options = ComboBoxOption::where("tag_id", $tag_id)->get();


        if ($request->input('type') == "combo") {
            $this->validate($request, [
                'name' => 'required',
                'options.*' => 'required|unique:document_tags_combo_options,value'
            ]);
        } else {
            $this->validate($request, [
                'name' => 'required',
            ]);
        }


//        if ($request->input('type') == "combo") {
//
//            foreach ($combo_options as $combo_option){
//
//                $combo_option->delete();
//
//            }
//
//            foreach ($request->input('options') as $comboOption) {
//
//                $data = [
//                    'tag_id' => $tag_id,
//                    'value' => $comboOption,
//
//                ];
//                ComboBoxOption::create($data);
//
//            }
//        }

        $tag->name = Input::get('name');

//        $tag->type = Input::get('type');
//        if(Input::get('type') == "combo"){
//
//            $tag->type = "string";
//
//        }
//        $tag->category = Input::get('category');

        $tag->save();

        return redirect()->route('view-tags', ['document' => $document->id, 'user_id' => $user->id]);
    }

    /**
     * Deletes the Collection Tag in the table collection_tags with the id = tag_id
     *
     * @param
     * @param
     * @throws
     * @return
     */
    public function destroy (Request $request, $tag_id){
        $document = Document::findOrFail($request->input('document_id'));
        $tag = CollectionTag::findOrFail($tag_id);
        $user = User::findOrFail($request->input('user_id'));

        //check if user can delete tag
        $this->authorize('delete', $document);

        $tag->delete();

        return redirect()->route('view-tags', ['document' => $document->id, 'user_id' => $user->id]);

    }


    /**
     * Show a form with a list of Collection Tags available to the user.
     * The user can assign new values to these tags for this document and store them in docuemnt_tags.
     * The user can also change the current values of the tags if they have one and update the correct
     * row in document_tags instead
     *
     * @param
     * @param
     * @param
     * @throws
     * @return
     */
    public function addTags(Request $request, $document_id, $user_id)
    {
        $document = Document::findOrFail($document_id);
        $user = User::findOrFail($user_id);

        //check if user can create document
        $this->authorize('update', $document);

        $collection = $document->getCollection();

        $userCollectionTags = CollectionTag::getUserTags($user->id, $collection->id);

        $categories = $userCollectionTags->unique('category');

        $comboOptions = ComboBoxOption::all();

        return view('/document/tagging', array('document' => $document, 'tags' => $userCollectionTags, 'comboOptions' => $comboOptions, 'categories' => $categories));
    }

    /**
     * Saves the current values assigned to each Collection Tag to the current document as Document Tags
     * in docuemnt_tags table
     *
     * The user can assign new values to these tags for this document and store them in docuemnt_tags.
     * The user can also change the current values of the tags if they have one and update the correct
     * row in document_tags instead
     *
     * form_data is an array of the values sent in the form with a structure seen below where the integer in
     * the key represents the corresponding CollectionTags id.
     * ValueN represents the default inputs in the form (text, integer, date/time, select box) while the
     * valueNother is a special case for the select boxes in the form.
     * Each select box in the form has a value "Other" at the bottom. When the user selects this value,
     * a hidden text input appears, these are named as valueNother and their values are the text the user inputs.
     *
     * form_data{
     *              "value1"        =>      'Unknown',                  <---  1)
     *              "value1other'   =>      null,
     *              "value2"        =>      "[not set]",                <---  2)
     *              "value2other"   =>      "Device",

resources/views/tags/create.blade.php
@extends('layouts.app')
@section('extrajs')
   <script src="/js/form.js"></script>
@endsection
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create a new Tag to use</div>

                    <div class="panel-body">



                        <form class="form-horizontal" method="POST" action="{{ route('tag.store') }}">
                            {{ csrf_field() }}
                            {{ Form::hidden('user_id', Auth::user()->id) }}
                            {{ Form::hidden('document_id', $document->id) }}

                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif


                            <div class="form-group">
                                <label for="name" class="col-md-4 control-label">Name</label>
                                <div class="col-md-6">
                                    <input type="text" name="name" id="name" class="form-control" placeholder="Enter the name">

                                </div>


                            </div>


                            <div class="form-group">
                                <label for="category" class="col-md-4 control-label">Category</label>
                                <div class="col-md-6">
                                    <select id="type" name="category" class="form-control selectBox">
                                        <option>Document</option>
                                        <option>Sender</option>
                                        <option>Recipient</option>
                                    </select>

                                </div>

                            </div>

                            <div class="form-group">
                                <label for="type" class="col-md-4 control-label">Type</label>
                                <div class="col-md-6">
                                    <select id="type" name="type" class="form-control selectBox">
                                        <option selected disabled hidden>Please select one option</option>

                                        @foreach($types as $type)

                                            @if($type=='combo')
                                                <option data-show="1">combo</option>
                                            @else
                                                <option>{{$type}}</option>
                                            @endif
                                        @endforeach

                                    </select>



                                </div>

                            </div>


                            <div class="form-group" id="1" style="display: none;">
                                <label class="col-md-4 control-label">Combo Options</label>
                                <div class="col-md-4" id="options">
                                    <button type="button" class="btn btn-primary" id="added" data-show="add">Add</button>
                                    <button type="button" class="btn btn-primary " id="removed">Remove</button>

                                    <input type="text" name="options[]" class="form-control" placeholder="Enter an option">
                                    <input type="text" name="options[]" class="form-control" placeholder="Enter an option">

                                </div>


                            </div>
                            

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">

                                    <input type="submit" class="btn btn-primary" value="Create">

                                </div>

                            </div>

                        </form>


                        <div class="col-md-8 col-md-offset-4">
                            {{--back button--}}
                            {{ Form::open(array('route' => array('add-tags', $document->id, 'user_id'=>Auth::user()->id))) }}
                            {{ Form::hidden('_method', 'GET') }}
                            {{ Form::submit('Back', array('class' => 'btn btn-primary')) }}
                            {{ Form::close() }}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tags/edit.blade.php
@extends('layouts.app')
@section('extrajs')
    <script src="/js/form.js"></script>
@endsection
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Update tag for {{$tag->name}}</div>

                    <div class="panel-body">

                        {{ Form::open(array('route' => array('tag.update', $tag->id )))}}

                        {{ csrf_field() }}
                        {{ method_field("PUT") }}
                        {{ Form::hidden('user_id', Auth::user()->id) }}
                        {{ Form::hidden('document_id', $document->id) }}



                    @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif


                            <div class="form-group">
                                <label for="name" class="col-md-4 control-label">Name</label>
                                <div class="col-md-6">
                                    <input type="text" name="name" id="name" class="form-control" value="{{$tag->name}}">

                                </div>


                            </div>


                            {{--<div class="form-group">--}}
                                {{--<label for="description" class="col-md-4 control-label">Category</label>--}}
                                {{--<div class="col-md-6">--}}
                                    {{--<select id="type" name="category" class="form-control selectBox">--}}
                                        {{--@if ($tag->category == 'Document')--}}
                                            {{--<option selected>Document</option>--}}
                                            {{--<option>Sender</option>--}}
                                            {{--<option>Recipient</option>--}}
                                        {{--@elseif ($tag->category == 'Sender')--}}
                                            {{--<option selected>Sender</option>--}}
                                            {{--<option>Document</option>--}}
                                            {{--<option>Recipient</option>--}}

                                        {{--@elseif ($tag->category == 'Recipient')--}}
                                            {{--<option selected>Recipient</option>--}}
                                            {{--<option>Document</option>--}}
                                            {{--<option>Sender</option>--}}
                                        {{--@endif--}}
                                    {{--</select>--}}

                                {{--</div>--}}

                            {{--</div>--}}

                            {{--<div class="form-group">--}}
                                {{--<label for="description" class="col-md-4 control-label">Type</label>--}}
                                {{--<div class="col-md-6">--}}
                                    {{--<select id="type" name="type" class="form-control selectBox">--}}
                                        {{--@if ($tag->isCombo())--}}
                                            {{--<option>string</option>--}}
                                            {{--<option>integer</option>--}}
                                            {{--<option>timestamp</option>--}}
                                            {{--<option selected data-show="1">combo</option>--}}
                                        {{--@elseif ($tag->isInteger())--}}
                                            {{--<option>string</option>--}}
                                            {{--<option selected>integer</option>--}}
                                            {{--<option>timestamp</option>--}}
                                            {{--<option data-show="1">combo</option>--}}
                                        {{--@elseif ($tag->isTimestamp())--}}
                                            {{--<option>string</option>--}}
                                            {{--<option >integer</option>--}}
                                            {{--<option selected>timestamp</option>--}}
                                            {{--<option data-show="1">combo</option>--}}
                                        {{--@elseif ($tag->isString())--}}
                                            {{--<option selected>string</option>--}}
                                            {{--<option >integer</option>--}}
                                            {{--<option >timestamp</option>--}}
                                            {{--<option data-show="1">combo</option>--}}


                                        {{--@endif--}}

                                    {{--</select>--}}



                                {{--</div>--}}

                            {{--</div>--}}


                            <div class="form-group" id="1" style="display: none;">
                                <label class="col-md-4 control-label">Combo Options</label>
                                <div class="col-md-4" id="options">
                                    <button type="button" class="btn btn-primary" id="added" data-show="add">Add</button>
                                    <button type="button" class="btn btn-primary " id="removed">Remove</button>

                                    <input type="text" name="options[]" class="form-control" placeholder="Enter an option">
                                    <input type="text" name="options[]" class="form-control" placeholder="Enter an option">

                                </div>

                            </div>


                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    {{ Form::submit('Update', array('class' => 'btn btn-primary')) }}


                                </div>

                            </div>

                        {{ Form::close() }}


                        <div class="col-md-8 col-md-offset-4">
                            {{--back button--}}
                            {{ Form::open(array('route' => array('view-tags', $document->id, 'user_id'=>Auth::user()->id))) }}
                            {{ Form::hidden('_method', 'GET') }}
                            {{ Form::submit('Back', array('class' => 'btn btn-primary')) }}
                            {{ Form::close() }}
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection