routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::resource('collections', 'CollectionController');
Route::get('collections/{collection_id}/create_series', 'SeriesController@create')->name('series-create');
Route::get('collections/{collection_id}/permissions', 'CollectionPermissionController@index' )->name('collection_permission');
Route::post('collections/{collection_id}/permissions/update', 'CollectionPermissionController@update' )->name('update_permissions');

Route::resource('series', 'SeriesController');
Route::get('series/{series_id}/create_document', 'DocumentController@create')->name('document-create');

Route::resource('documents', 'DocumentController');
Route::get('documents/{document_id}/pdf', 'DocumentController@pdf')->name('document-pdf');
Route::get('documents/{document_id}/digitise', 'DocumentController@createDigitisedText' )->name('create-digitised');
Route::post('documents/{document_id}/digitise/store', 'DocumentController@storeDigitisedText' )->name('store-digitised');

Route::get('documents/{document_id}/tag/add/{user_id}', 'DocumentController@addTags' )->name('add-tags');
Route::get('documents/{document_id}/tag/view/{user_id}', 'DocumentController@viewTags' )->name('view-tags');
Route::get('documents/{document_id}/tag/edit/{user_id}/{tag_id}', 'DocumentController@editTags' )->name('edit-tag');
Route::post('documents/{document_id}/tag/store/{user_id}', 'DocumentController@storeTags' )->name('store-tags');

Route::get('documents/{document_id}/tag/add/{user_id}', 'DocumentController@addTags' )->name('add-tags');
Route::get('documents/{document_id}/tag/view/{user_id}', 'DocumentController@viewTags' )->name('view-tags');
Route::get('documents/{document_id}/tag/edit/{user_id}/{tag_id}', 'DocumentController@editTags' )->name('edit-tag');
Route::post('documents/{document_id}/tag/store/{user_id}', 'DocumentController@storeTags' )->name('store-tags');

Route::resource('tag', 'TagController');
Route::get('documents/{document_id}/tag/view/{user_id}', 'TagController@viewTags' )->name('view-tags');
Route::get('documents/{document_id}/tag/edit/{user_id}/{tag_id}', 'TagController@editTags' )->name('edit-tags');
Route::get('documents/{document_id}/tag/add/{user_id}', 'TagController@addTags' )->name('add-tags');
Route::post('documents/{document_id}/tag/store/{user_id}', 'TagController@storeTags' )->name('store-tags');
Route::get('documents/{document_id}/tag/create', 'TagController@createNewTag' )->name('create-tag');

app/Http/Controllers/SeriesController.php
<?php

namespace App\Http\Controllers;

use App\Collection;
use App\Document;
use App\Series;
use DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

/**
 * Class SeriesController.
 *
 * This class controls the CRUD of series from a relation database
 *
 * @author Daniel Sutton
 */
class SeriesController extends Controller
{

    /**
     * Show a create form for creating a series
     *
     * @param int $id
     *          The id of the collection that the series will belong to
     * @return view to create a series
     */
    public function create($id)
    {
        $collection = Collection::find($id);

        //check if user can create series
        $this->authorize('createSeries', $collection);

        return view('/series/create', array('collection'=>$collection));
    }

    /**
     * Store a series in database by inserting given form data from Request.
     *
     * @param Request $request
     *      The POST request containing the data from the series create form
     * @return series, URL /series, route(series.index), calls index() view of all series
     */
    public function store(Request $request)
    {
        $collection = Collection::find($request->input('collection_id'));

        //check if user can create series
        $this->authorize('createSeries', $collection);

        $this->validate($request, [
            'name' => 'required|unique:series',
            'description'=>'required',
        ]);

        //data that will be inserted into new row in series table
        $data = [
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'collection_id' => $request->input('collection_id')
        ];

        //create a series using the POST data
        Series::create($data);


        //return $controller->show($data['collection_id']);
        return redirect()->route('collections.show' , ['collection' => $data['collection_id']]);
    }

    /**
     * Display a specific series from a query from the database.
     *
     * @param  int  $id
     *      The id of the given series to be retrieved from the series table in database
     * @return The view of the chosen series
     */
    public function show($id)
    {
        //retreives the series from DB with given id
        $series = Series::find($id);

        //check if user can view series
        $this->authorize('view', $series);

        $documents = Document::all()->where('series_id', $series->id);

        //array contains a single series from the DB with all attributes {name, description}
        //This info will be displayed in view
        return view('/series/view', array('series'=>$series, 'documents'=>$documents));
    }

    /**
     * Show the series and edit it.
     *
     * @param  int  $id
     *      The id of the given series to be retrieved from the series table in database
     * @return The edit page with the chosen series as an arguement
     */
    public function edit($id)
    {
        //retreives the series from DB with given id
        $series = Series::find($id);

        //check if user can edit series
        $this->authorize('update', $series);

        //array contains a single series from the DB with all attributes {name, description...}
        //This info will used as placeholders in series edit form
        return view('/series/edit', array('series'=>$series));
    }

    /**
     * Update a specific series in the DB with information from the series edit form
     *
     * @param  int  $id
     *      The id of the given series to be retrieved from the series table in database and edited
     * @return The view page of the given series with the series as an argument using the updated information and
     */
    public function update($id, Request $request)
    {
        //find series
        $series = Series::find($id);

        //check if user can edit series
        $this->authorize('update', $series);

        //If validation passes, code will continue executing normally.
        //However, if validation fails, an  Illuminate\Contracts\Validation\ValidationException will be thrown
        //and is automatically caught and a redirect to the user's previous location.
        $this->validate($request, ['name' => 'required|unique:series',
            'description'=>'required',
        ]);

        //update existing columns
        $series->name           = Input::get('name');
        $series->description    = Input::get('description');
        $series->save();

        return redirect()->route('series.show' , ['series' => $series]);

    }

    /**
     * Delete a specific series from the database.
     *
     * @param  int  $id
     *      id of series to remove
     * @return
     *      CollectionController::show, the view of the collection with a list of series
     */
    public function destroy($id)
    {
        //find series
        $series = Series::find($id);

        //check if user can delete series
        $this->authorize('delete', $series);

        //find collection associated w series
        $collection = $series->collection()->first();

        $series->delete();

        return redirect()->route('collections.show' , ['collection' => $collection]);
    }

}

resources/views/series/create.blade.php
@extends('layouts.app')
@section('extracss')
    <link rel="stylesheet" href="/js/pdfjs/web/buttonFormat.css">
@endsection
@section('content')
    <div class="container">
        <div class="col-sm-4 col-sm-offset-8">
            {{--back button--}}
            {{ Form::open(array('route' => array('collections.show', $collection->id))) }}
            {{ Form::hidden('_method', 'GET') }}
            {{ Form::submit('Back', array('class' => 'btn btn-primary')) }}
            {{ Form::close() }}
        </div>
        <div class="row">
            <div class="col-sm-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create A New Series</div>

                    <div class="panel-body">

                        {{ Form::open(array('route' => 'series.store')) }}
                        {{ csrf_field() }}
                        {{ Form::hidden('collection_id', $collection->id) }}

                        <div class="col-sm-12">
                            {{ Form::label('name', 'Series title') }}
                            {{ Form::text('name', "", ['style'=>'border-bottom-width:1px;'], ['placeholder' => 'Enter the title']) }}
                        </div>
                        @foreach ($errors->get('name') as $error)
                            <div class="alert alert-danger">{{ $error }}</div>
                        @endforeach

                        <div class="col-sm-12">
                            {{ Form::label('description', 'Series description') }}
                            {{ Form::text('description', "", ['style'=>'width:100%; height:100px; border-bottom-width:1px;']) }}
                        </div>
                        @foreach ($errors->get('description') as $error)
                            <div class="alert alert-danger">{{ $error }}</div>
                        @endforeach

                        {{ Form::submit('Create', array('class' => 'btn btn-primary'), ["style"=>"padding:20px;"]) }}
                        {{ Form::close() }}


                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/series/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">edit series</div>

                    <div class="panel-body">

                        {{ Form::open(array('route' => array('series.update', $series->id))) }}
                        {{ csrf_field() }}
                        {{ method_field("PUT") }}

                        {{ Form::label('name', 'Series title') }}
                        {{ Form::text('name', $series->name) }}

                        @if ($errors->has('name'))
                            @if ($error = $errors->first('name'))
                                <div class="alert alert-danger">
                                    {{ $error }}
                                </div>
                            @endif
                        @endif

                        {{ Form::label('description', 'Series description') }}
                        {{ Form::text('description', $series->description) }}

                        @if ($errors->has('description'))
                            @if ($error = $errors->first('description'))
                                <div class="alert alert-danger">
                                    {{ $error }}
                                </div>
                            @endif
                        @endif

                        {{ Form::submit('Update', array('class' => 'btn btn-primary')) }}
                        {{ Form::close() }}

                        <div class="col-md-8 col-md-offset-4">
                            {{--back button--}}
                            {{ Form::open(array('route' => array('series.show', $series->id))) }}
                            {{ Form::hidden('_method', 'GET') }}
                            {{ Form::submit('Back', array('class' => 'btn btn-primary')) }}
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/series/view.blade.php
@extends('layouts.app')
@section('extracss')
    <link rel="stylesheet" href="/js/pdfjs/web/buttonFormat.css">
@endsection
@section('content')
    <section class="section-60 section-sm-100">
        <div class="shell text-center text-md-center">
            <div class="range range-md-middle range-md-center">

            @can('createDocument', $series)
                <!-- The Current User Can Add A New Document -->
                    {{--create button--}}
                    {{ Form::open(array('route' => array('document-create', $series->id ))) }}
                    {{ Form::hidden('_method', 'GET') }}
                    {{ Form::submit('Create Document', array('class' => 'btn btn-primary')) }}
                    {{ Form::close() }}
            @endcan

            </div>
        </div>
    </section>

     <div class="row">
        <div class="col-sm-8 col-sm-push-2">
            <div class="panel panel-default">

                <div class="panel-heading">
                    <h3 class="panel-heading">{{$series->name}}</h3>
                </div>

                <div class="panel-body content">
                    <p><strong>Description:</strong></p>
                    {!! $series->description !!}
                </div>

                {{--table for series--}}
                <table class="table table-bordered table-hover table-striped">
                    <tbody>
                    @foreach($documents as $document)
                        @can('view', $document)
                            <tr>
                                <td>
                                    <a href="{{ route('documents.show', $document->id) }}"/>{{ $document->title }}
                                </td>
                            </tr>
                        @endcan
                    @endforeach
                    </tbody>
                </table>

            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-3">
                    @can('update', $series)
                    <!-- The Current User Can edit The collection -->
                        {{--edit button--}}
                        {{ Form::open(array('route' => array('series.edit', $series))) }}
                        {{ Form::hidden('_method', 'GET') }}
                        {{ Form::submit('Edit Series', array('class' => 'btn btn-primary')) }}
                        {{ Form::close() }}
                    @endcan
                </div>
                <div class="col-sm-3">
                    @can('delete', $series)
                        {{--delete button--}}
                        {{ Form::open(array('route' => array('series.destroy', $series))) }}
                        {{ Form::hidden('_method', 'DELETE') }}
                        {{ Form::submit('Delete series', array('class' => 'btn btn-primary')) }}
                        {{ Form::close() }}
                    @endcan
                </div>
                <div class="col-sm-3">
                    {{--back button--}}
                    {{ Form::open(array('route' => array('collections.show', $series->collection_id))) }}
                    {{ Form::hidden('_method', 'GET') }}
                    {{ Form::submit('Back', array('class' => 'btn btn-primary')) }}
                    {{ Form::close() }}
                </div>

            </div>


        </div>
    </div>

@endsection