routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::resource('collections', 'CollectionController');
Route::get('collections/{collection_id}/create_series', 'SeriesController@create')->name('series-create');
Route::get('collections/{collection_id}/permissions', 'CollectionPermissionController@index' )->name('collection_permission');
Route::post('collections/{collection_id}/permissions/update', 'CollectionPermissionController@update' )->name('update_permissions');

Route::resource('series', 'SeriesController');
Route::get('series/{series_id}/create_document', 'DocumentController@create')->name('document-create');

Route::resource('documents', 'DocumentController');
Route::get('documents/{document_id}/pdf', 'DocumentController@pdf')->name('document-pdf');
Route::get('documents/{document_id}/digitise', 'DocumentController@createDigitisedText' )->name('create-digitised');
Route::post('documents/{document_id}/digitise/store', 'DocumentController@storeDigitisedText' )->name('store-digitised');

Route::get('documents/{document_id}/tag/add/{user_id}', 'DocumentController@addTags' )->name('add-tags');
Route::get('documents/{document_id}/tag/view/{user_id}', 'DocumentController@viewTags' )->name('view-tags');
Route::get('documents/{document_id}/tag/edit/{user_id}/{tag_id}', 'DocumentController@editTags' )->name('edit-tag');
Route::post('documents/{document_id}/tag/store/{user_id}', 'DocumentController@storeTags' )->name('store-tags');

Route::get('documents/{document_id}/tag/add/{user_id}', 'DocumentController@addTags' )->name('add-tags');
Route::get('documents/{document_id}/tag/view/{user_id}', 'DocumentController@viewTags' )->name('view-tags');
Route::get('documents/{document_id}/tag/edit/{user_id}/{tag_id}', 'DocumentController@editTags' )->name('edit-tag');
Route::post('documents/{document_id}/tag/store/{user_id}', 'DocumentController@storeTags' )->name('store-tags');

Route::resource('tag', 'TagController');
Route::get('documents/{document_id}/tag/view/{user_id}', 'TagController@viewTags' )->name('view-tags');
Route::get('documents/{document_id}/tag/edit/{user_id}/{tag_id}', 'TagController@editTags' )->name('edit-tags');
Route::get('documents/{document_id}/tag/add/{user_id}', 'TagController@addTags' )->name('add-tags');
Route::post('documents/{document_id}/tag/store/{user_id}', 'TagController@storeTags' )->name('store-tags');
Route::get('documents/{document_id}/tag/create', 'TagController@createNewTag' )->name('create-tag');

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'anon_title', 'description', 'series_id' ,'raw_doc','URL_page',
        'URL_access_date','doc_type_id'
    ];

    /**
     * @var array These attributes are hidden
     */
    protected $guarded = ['id', 'created_at', 'updated_at'];

    /**
     *  Document belongs to a series
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     *          Series object that the Document belongs to using the series_id attribute
     */
    public function series()
    {
        //belongsTo because document have series_id, NOT hasOne, as foreign key is loacated in document table
        return $this->belongsTo('App\Series', 'series_id');
    }

    /**
     *  Document belongs to a series, which belongs to a collection. This returns the collection
     * @return Collection
     */
    public function getCollection()
    {
        return $this->series()->first()->collection()->first();
    }

    /**
     * Returns the value of a collection tag based on its ID determining if it
     * is a string, timestamp, integer or combo
     *
     * @param $col_tag_id
     * @return string
     */
    public function getValueFor($col_tag_id){

        $collectionTag = CollectionTag::findOrFail($col_tag_id);
        $doc_tag = DocumentTag::where('tag_id', $collectionTag->id)->where('document_id', $this->id)->first();

        //when a document is first created, no document_tags are created therefore null is returned.
        //Once document tag value are saved, document tags are created and then values are returned
        if($doc_tag) {

            if($collectionTag->isString()){

                return $doc_tag->text_value;

            }
            elseif($collectionTag->isTimestamp()){

                $datetime = explode( " " , $doc_tag->tstamp_value);
                $formatted_datetime = $datetime[0]."T".$datetime[1];

                return $formatted_datetime;

            }
            elseif($collectionTag->isInteger()) {

                return $doc_tag->int_value;

            }
        }else{
            return null;
        }
    }

    /**
     *  This function takes an array with structure {collection_tag_id => value) and confirms
     * if the document tag values match with the values in the array.
     *
     * If the corresponding collection tag exits, and if there are document tags existing
     * with the collection tag and these document tags have values equal to value is array.
     */
    public function matchesTags($tagFilter){
        foreach ($tagFilter as $key => $value){
            $value_id = preg_split("/(?<=[a-z])(?=\d)/", $key);
            $tag_id = $value_id[1];

            $tag = CollectionTag::findOrFail($tag_id);
            //find collection tag assigned to this document
            $doc_tags = DocumentTag::where('tag_id', $tag->id)->where('document_id', $this->id)->get();

            if (count($doc_tags) == 0) {
                return false;
            }

            foreach ($doc_tags as $doc_tag){
                if ($tag->isString() && $doc_tag->text_value == $value ){
                    // match
                }
                elseif ($tag->isTimestamp() && $doc_tag->tstamp_value == $value){
                    // match
                }
                elseif ($tag->isInteger() && $doc_tag->int_value == $value) {
                    // match
                }
                else {
                    return false;
                }
            }
        }
        return true;
    }

    /**
     *  This function checks if document tag text_value is a combo option in the document_tags_combo_options table, if the text_value is also a value
     *  in the combo options table for the same collection tag, return true, otherwise false as it is a not default value
     */
    public function checkIfComboOption($col_tag_id){

        $collectionTag = CollectionTag::findOrFail($col_tag_id);
        if (!$collectionTag->isCombo()) {
            return false;
        }

        $doc_tag = DocumentTag::where('tag_id', $collectionTag->id)->where('document_id', $this->id)->first();
        if (!$doc_tag) {
            return false;
        }

        $combo_options = ComboBoxOption::where('tag_id', $collectionTag->id)->get();
        $combo_option_norm_values = [];
        foreach ($combo_options as $combo_option){
            $combo_option_norm_values[] = $this->normalizeComboValue($combo_option->value);
        }
        $norm_text_value = $this->normalizeComboValue($doc_tag->text_value);

        //if document tag value not in array of combo options, then it is an other value
        return !in_array($norm_text_value, $combo_option_norm_values);
    }

    private function normalizeComboValue($value) {
        $value = str_replace(" ", "", $value);
        $value = strtolower($value);
        return $value;
    }

    /**
     * Returns the true if there is a document tag assigned to the document given a collection tag, otherwise false.
     *
     * @param $col_tag_id
     * @return boolean
     */
    public function checkIfDocTagAssigned($col_tag_id){

        $collectionTag = CollectionTag::findOrFail($col_tag_id);
        $doc_tag = DocumentTag::where('tag_id', $collectionTag->id)->where('document_id', $this->id)->first();
        if($doc_tag){
            return true;
        }

        return false;
    }
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use App\Document;
use App\Series;
use DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;


class DocumentController extends Controller
{
    /**
     * Show a create form for creating a document
     *
     * @return
     */
    public function create($id)
    {
        $series = Series::find($id);

        //check if user can create document
        $this->authorize('createDocument', $series);

        return view('/document/create', array('series' => $series));
    }

    /**
     * Store a document in database by inserting given form data from Request.
     *
     * @param Request $request
     *      The POST request containing the data from the document create form
     * @return SeriesController@show, returns view of series with list of all documents including newly created one
     */
    public function store(Request $request)
    {
        $series = Series::find($request->input('series_id'));

        //check if user can create document
        $this->authorize('createDocument', $series);

        $this->validate($request, [
            'title' => 'required|unique:documents',
            'description' => 'required',
            'document' => 'mimes:pdf',
        ]);

        $file = null;

        if ($request->file('document')) {
            $file = base64_encode(file_get_contents($request->file('document')));
        }


        //data that will be inserted into new row in document table
        $data = [
            'title' => $request->input('title'),
            'anon_title' => $request->input('anontitle'),
            'description' => $request->input('description'),
            'raw_doc' => $file,
            'URL_page' => $request->input('URL_page'),
            'URL_access_date' => $request->input('URL_access_date'),
            'series_id' => $request->input('series_id'),
            'doc_type_id' => $request->input('doc_type_id'),
        ];

        //create a document using the POST data
        Document::create($data);


        return redirect()->route('series.show', ['series' => $data['series_id']]);
    }

    /**
     * Display a specific document from a query from the database.
     *
     * @param  int $id
     *      The id of the given document to be retrieved from the document table in database
     * @return The view of the chosen document
     */
    public function show($id)
    {
        //retreives the document from DB with given id
        $document = Document::find($id);

        //check if user can view document
        $this->authorize('view', $document);

        //array contains a single document from the DB with all attributes {name, description...}
        //This info will be displayed in view
        return view('/document/view', array('document' => $document));
    }

    /**
     * Get the document ready for showing
     */
    public function getDocument($id)
    {
        //retreives the document from DB with given id
        $document = Document::find($id);

        //check if user can edit document
        $this->authorize('update', $document);

        return view('documents/{id}/pdf', array('document' => $document));
    }

    /**
     * Show the document and edit it.
     *
     * @param  int $id
     *      The id of the given document to be retrieved from the document table in database
     * @return The edit page with the chosen document as an argument
     */
    public function edit($id)
    {
        //retreives the document from DB with given id
        $document = Document::find($id);

        //check if user can edit document
        $this->authorize('update', $document);

        //array contains a single document from the DB with all attributes {name, description...}
        //This info will used as placeholders in document edit form
        return view('/document/edit', array('document' => $document));
    }

    /**
     * Update a specific document in the DB with information from the document edit form
     *
     * @param  int $id
     *      The id of the given document to be retrieved from the document table in database and edited
     * @return The view page of the given document with the document as an argument using the updated information and
     */
    public function update($id, Request $request)
    {
        //find document
        $document = Document::find($id);

        //check if user can edit document
        $this->authorize('update', $document);

        //If validation passes, code will continue executing normally.
        //However, if validation fails, an  Illuminate\Contracts\Validation\ValidationException will be thrown
        //and is automatically caught and a redirect to the user's previous location.
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'document' => 'mimes:pdf',
        ]);
        $file = null;
        if ($request->file('document')) {
            $file = base64_encode(file_get_contents($request->file('document')));
        }
        else{

            $file = $document->raw_doc;
        }
        //update existing columns
        $document->title = Input::get('title');
        $document->description = Input::get('description');
        $document->title = Input::get('title');
        $document->anon_title = Input::get('anontitle');
        $document->description = Input::get('description');
        $document->raw_doc = $file;
        $document->URL_page = Input::get('URL_page');
        $document->URL_access_date = Input::get('URL_access_date');
        $document->save();

        return redirect()->route('documents.show', ['documents' => $document['id']]);
    }

    /**
     * Delete a specific document from the database.
     *
     * @param  int $id
     *      id of document to remove
     * @return
     *      SeriesController::show, the view of the series with a list of documents
     */
    public function destroy($id)
    {
        //find document
        $document = Document::find($id);

        //check if user can delete document
        $this->authorize('delete', $document);

        //find collection associated w series
        $series = $document->series()->first();

        $document->delete();

        return redirect()->route('series.show', ['series' => $series]);

    }

    public function pdf($id)
    {
        //find document
        $document = Document::find($id);

        //check if user can view document
        $this->authorize('view', $document);

        $file_contents = base64_decode($document->raw_doc);

        return response($file_contents)
            ->header('Cache-Control', 'no-cache private')
            ->header('Content-Description', 'File Transfer')
            ->header('Content-Type', 'application/x-pdf')
            ->header('Content-Length', strlen($file_contents))
            ->header('Content-Disposition', 'inline; filename="example.pdf"')
            ->header('Content-Transfer-Encoding', 'binary');
    }

    /**
     * Show a create form for creating a digitised text of the document
     *
     * @return
     */
    public function createDigitisedText($id)
    {
        $document = Document::find($id);

        //check if user can create document
        $this->authorize('update', $document);

        return view('/document/digitised', array('document' => $document));
    }


    /**
     * Update a specific document in the DB with the digitised text
     *
     * @param  int $id
     *      The id of the given document to be retrieved from the document table in database and edited
     * @return The view page of the given document with the document as an argument using the updated information and
     */
    public function storeDigitisedText($id, Request $request)
    {
        //find document
        $document = Document::find($id);

        //check if user can edit document
        $this->authorize('update', $document);

        //If validation passes, code will continue executing normally.
        //However, if validation fails, an  Illuminate\Contracts\Validation\ValidationException will be thrown
        //and is automatically caught and a redirect to the user's previous location.
        $this->validate($request, [
            'text' => 'required',
        ]);

        //update existing columns
        $document->digitised_text = Input::get('text');
        $document->save();

        return redirect()->route('documents.show', ['documents' => $document['id']]);
    }


}

resources/views/document/create.blade.php
@extends('layouts.app')
@section('extracss')
    <link rel="stylesheet" href="/js/pdfjs/web/buttonFormat.css">
@endsection
@section('content')
    <div class="container">
        <div class="col-sm-4 col-sm-offset-8">
            {{--back button--}}
            {{ Form::open(array('route' => array('series.show', $series->id))) }}
            {{ Form::hidden('_method', 'GET') }}
            {{ Form::submit('Back', array('class' => 'btn btn-primary')) }}
            {{ Form::close() }}
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create A New Document</div>

                    <div class="panel-body">
                        <form class="form-horizontal" enctype="multipart/form-data" method="POST" action="{{ route('documents.store') }}">
                            {{ csrf_field() }}
                            {{ Form::hidden('series_id', $series->id) }}

                            <div class="form-group">
                                <label for="title" class="col-md-4 control-label">Title</label>
                                <div class="col-md-6">
                                    <input type="text" name="title" id="title" class="form-control" placeholder="Enter the title"  autofocus>
                                </div>

                            </div>
                            @if ($errors->has('title'))
                                @if ($error = $errors->first('title'))
                                    <div class="alert alert-danger">
                                        {{ $error }}
                                    </div>
                                @endif
                            @endif

                            <div class="form-group">
                                <label for="description" class="col-md-4 control-label">Description</label>
                                <div class="col-md-6">
                              <textarea
                                      id="description"
                                      name="description" class="form-control"
                                      placeholder="Enter the description" ></textarea>
                                </div>

                            </div>
                            @if ($errors->has('description'))
                                @if ($error = $errors->first('description'))
                                    <div class="alert alert-danger">
                                        {{ $error }}
                                    </div>
                                @endif
                            @endif
                            <div class="form-group">
                                <label for="document" class="col-md-4 control-label">Add a document file</label>
                                <div class="col-md-6">
                                    {{Form::file('document', ['class' => 'form-control', 'accept' => 'application/pdf'])}}
                                </div>

                            </div>
                            @if ($errors->has('document'))
                                @if ($error = $errors->first('document'))
                                    <div class="alert alert-danger">
                                        {{ $error }}
                                    </div>
                                @endif
                            @endif

                            <div class="form-group">
                                <label for="title" class="col-md-4 control-label">Anonymised Title</label>
                                <div class="col-md-6">
                                    <input type="text" name="anontitle" id="anontitle" class="form-control" placeholder="Enter the anonymised title" autofocus>
                                </div>

                            </div>
                            @if ($errors->has('anontitle'))
                                @if ($error = $errors->first('anontitle'))
                                    <div class="alert alert-danger">
                                        {{ $error }}
                                    </div>
                                @endif
                            @endif

                            <div class="form-group">
                                <label for="title" class="col-md-4 control-label">URL page</label>
                                <div class="col-md-6">
                                    <input type="text" name="urlpage" id="urlpage" class="form-control" autofocus>
                                </div>

                            </div>
                            @if ($errors->has('urlpage'))
                                @if ($error = $errors->first('urlpage'))
                                    <div class="alert alert-danger">
                                        {{ $error }}
                                    </div>
                                @endif
                            @endif
                            <div class="form-group">
                                <label for="date" class="col-md-4 control-label">URL accessed date</label>
                                <div class="col-md-6">
                                    <input type="date" name="date" id="date" class="form-control"
                                           >

                                </div>
                            </div>
                            @if ($errors->has('date'))
                                @if ($error = $errors->first('date'))
                                    <div class="alert alert-danger">
                                        {{ $error }}
                                    </div>
                                @endif
                            @endif

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">

                                        <input type="submit" class="btn btn-primary" value="Create">

                                </div>

                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/document/digitised.blade.php
@extends('layouts.app')
<!--extend the main template so you can then add it-->
<!--Extend the extracss and extrajs sections to add the css style sheets and javascript specific to this page-->
@section('extracss')
    <link rel="stylesheet" href="/js/pdfjs/web/viewer.css">
    <link rel="resource" type="application/l10n" href="/js/pdfjs/web/locale/locale.properties">
    <link rel="stylesheet" href="/js/pdfjs/web/buttonFormat.css">
@endsection
@section('extrajs')
    <script src="/js/pdfjs/build/pdf.worker.js"></script>
    <script src="/js/pdfjs/build/pdf.js"></script>
    <script src="/js/pdfjs/web/viewer.js"></script>
@endsection
<!--Extend the content section to fill in the content of the page-->
@section('content')
    <div class="col-sm-offset-9">
        {{--back button--}}
        {{ Form::open(array('route' => array('documents.show', $document->id))) }}
        {{ Form::hidden('_method', 'GET') }}
        {{ Form::submit('Back', array('class' => 'btn btn-primary')) }}
        {{ Form::close() }}
    </div>

    <div class="container">
        <div class="panel panel-default">

            <div class="panel-heading col-sm-8">
                <h3 class="panel-heading">{{$document->title}}</h3>
            </div>
                <div class="panel-body content">

                    <div class="col-xs-12 col-sm-6">
                        @if($document->raw_doc != null)
                            <script type="text/javascript" >
                                $(function() { PDFViewerApplication.open('/documents/{{$document->id}}/pdf'); });
                            </script>
                            <div class="panel-body content">
                                <p><strong>Document</strong></p>
                                <div style="width:500px; height: 700px; border: solid;" >
                                    @include('document.pdfjs')
                                    <div id="printContainer"></div>
                                </div>

                            </div>
                        @endif
                    </div>

                    <div class="col-xs-12 col-sm-6">

                        {{ Form::open(array('route' => array('store-digitised', $document->id))) }}
                        {{ csrf_field() }}

                        {{ Form::label('text', 'Digitised Text') }}
                        {{ Form::textarea('text', $document->digitised_text, ['style'=>'width:100%; border:inset;'], ['placeholder' => 'Enter the digitised text']) }}

                        {{ Form::submit('Save', array('class' => 'btn btn-primary')) }}
                        {{ Form::close() }}

                    </div>
                </div>
            </div>
    </div>
@endsection

resources/views/document/edit.blade.php
@extends('layouts.app')
@section('extracss')
    <link rel="stylesheet" href="/js/pdfjs/web/buttonFormat.css">
@endsection
@section('content')
    <div class="container">
        <div class="col-sm-4 col-sm-offset-8">
            {{--back button--}}
            {{ Form::open(array('route' => array('documents.show', $document->id))) }}
            {{ Form::hidden('_method', 'GET') }}
            {{ Form::submit('Back', array('class' => 'btn btn-primary')) }}
            {{ Form::close() }}
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit Document</div>

                    <div class="panel-body">
                        <form class="form-horizontal" enctype="multipart/form-data" method="POST" action="{{ route('documents.update' ,['documents' => $document->id])}}">
                            {{ csrf_field() }}
                            {{ method_field("PUT") }}

                            <div class="form-group">
                                <label for="title" class="col-md-4 control-label">Title</label>
                                <div class="col-md-6">
                                    <input type="text" name="title" id="title" value="{{$document->title}}" class="form-control" placeholder="Enter the title"  autofocus>
                                </div>

                            </div>


                            <div class="form-group">
                                <label for="description" class="col-md-4 control-label">Description</label>
                                <div class="col-md-6">
                              <textarea
                                      id="description"
                                      name="description"  class="form-control"
                                      placeholder="Enter the description">{{$document->description}}</textarea>
                                </div>

                            </div>

                            <div class="form-group">
                                <label for="document" class="col-md-4 control-label">Add a document file</label>
                                <div class="col-md-6">
                                    {{Form::file('document', ['class' => 'form-control', 'accept' => 'application/pdf'])}}
                                </div>

                            </div>
                            @if ($errors->has('document'))
                                @if ($error = $errors->first('document'))
                                    <div class="alert alert-danger">
                                        {{ $error }}
                                    </div>
                                @endif
                            @endif

                            <div class="form-group">
                                <label for="title" class="col-md-4 control-label">Anonymised Title</label>
                                <div class="col-md-6">
                                    <input type="text" name="anontitle" id="anontitle" value="{{$document->anontitle}}" class="form-control" placeholder="Enter the anonymised title" autofocus>
                                </div>

                            </div>


                            <div class="form-group">
                                <label for="title" class="col-md-4 control-label">URL page</label>
                                <div class="col-md-6">
                                    <input type="text" name="urlpage" value="{{$document->URL_page}}" id="urlpage" class="form-control" autofocus>
                                </div>

                            </div>

                            <div class="form-group">
                                <label for="date" class="col-md-4 control-label">URL accessed date</label>
                                <div class="col-md-6">
                                    <input type="date" name="date" value="{{$document->URL_access_date}}" id="date" class="form-control"
                                    >

                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">

                                    <input type="submit" class="btn btn-primary" value="Update">

                                </div>

                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection