routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::resource('collections', 'CollectionController');
Route::get('collections/{collection_id}/create_series', 'SeriesController@create')->name('series-create');
Route::get('collections/{collection_id}/permissions', 'CollectionPermissionController@index' )->name('collection_permission');
Route::post('collections/{collection_id}/permissions/update', 'CollectionPermissionController@update' )->name('update_permissions');

Route::resource('series', 'SeriesController');
Route::get('series/{series_id}/create_document', 'DocumentController@create')->name('document-create');

Route::resource('documents', 'DocumentController');
Route::get('documents/{document_id}/pdf', 'DocumentController@pdf')->name('document-pdf');
Route::get('documents/{document_id}/digitise', 'DocumentController@createDigitisedText' )->name('create-digitised');
Route::post('documents/{document_id}/digitise/store', 'DocumentController@storeDigitisedText' )->name('store-digitised');

Route::get('documents/{document_id}/tag/add/{user_id}', 'DocumentController@addTags' )->name('add-tags');
Route::get('documents/{document_id}/tag/view/{user_id}', 'DocumentController@viewTags' )->name('view-tags');
Route::get('documents/{document_id}/tag/edit/{user_id}/{tag_id}', 'DocumentController@editTags' )->name('edit-tag');
Route::post('documents/{document_id}/tag/store/{user_id}', 'DocumentController@storeTags' )->name('store-tags');

Route::get('documents/{document_id}/tag/add/{user_id}', 'DocumentController@addTags' )->name('add-tags');
Route::get('documents/{document_id}/tag/view/{user_id}', 'DocumentController@viewTags' )->name('view-tags');
Route::get('documents/{document_id}/tag/edit/{user_id}/{tag_id}', 'DocumentController@editTags' )->name('edit-tag');
Route::post('documents/{document_id}/tag/store/{user_id}', 'DocumentController@storeTags' )->name('store-tags');

Route::resource('tag', 'TagController');
Route::get('documents/{document_id}/tag/view/{user_id}', 'TagController@viewTags' )->name('view-tags');
Route::get('documents/{document_id}/tag/edit/{user_id}/{tag_id}', 'TagController@editTags' )->name('edit-tags');
Route::get('documents/{document_id}/tag/add/{user_id}', 'TagController@addTags' )->name('add-tags');
Route::post('documents/{document_id}/tag/store/{user_id}', 'TagController@storeTags' )->name('store-tags');
Route::get('documents/{document_id}/tag/create', 'TagController@createNewTag' )->name('create-tag');

app/Collection.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Collection extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'owner_id',
    ];

    protected $guarded = ['id', 'created_at', 'updated_at'];


    /**
     *  Collection has an owner
     */
    public function owner()
    {
        return $this->belongsTo('App\User', 'owner_id');
    }

    /**
     *  Collection has many series
     */
    public function series()
    {
        //hasMany as series table has a collection_id column
        return $this->hasMany('App\Series', 'collection_id', 'id');
    }

    /**
     *  Collection has permissions
     */
    public function permissions()
    {
        //hasMany as collection_permissions table has a collection_id column
        return $this->hasMany('App\CollectionPermission');
    }

    /**
     *  Collection has many series, which then have many documents
     */
    public function documents()
    {
        //hasMany as series table has a collection_id column
        return $this->hasManyThrough('App\Series', 'App\Document',
                                    'series_id', 'collection_id',
                                    'id', 'id');
    }

    /**
     * returns an array of collections that the user has access to either by owning them
     * or they heve been given access to them
     */
    public static function getCollections($user_id){

        $collections = Collection::where('owner_id', $user_id)->get();

        $col_permissions = CollectionPermission::where('owner_id', $user_id)->where('permissions', 'view')->get();

        if(count($col_permissions)){
            foreach ($col_permissions as $col_permission){
                $collection = Collection::findOrFail($col_permission->collection_id);

                $collections[] = $collection;
            }
        }

        return $collections;
    }

}

app/Http/Controllers/CollectionController.php
<?php

namespace App\Http\Controllers;

use App\Collection;
use App\Series;
use DB;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;


/**
 * Class CollectionController.
 *
 * This class controls the CRUD of collections from a relation database
 *
 * @author Daniel Sutton
 */
class CollectionController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //this is so that users must be logged in to view collections
        $this->middleware('auth');
    }

    /**
     * Display a list of the collections.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // get collections from db
        $collections = Collection::all();

        // load the view and pass an array of collections
        return view('collection/index', array('collections' => $collections));
    }

    /**
     * Show a create form for creating a collection with a name and desc.
     *
     * @return
     */
    public function create()
    {
        //check if user can create collection
        $this->authorize('create', Collection::class);

        return view('collection/create');
    }

    /**
     * Store a collection in database by inserting given form data from Request.
     *
     * @param Request $request
     *      The POST request containing the data from the collection create form
     * @return collections, URL /collections, route(collections.index), calls index() view of all collections
     */
    public function store(Request $request)
    {
        //check if user can create collection
        $this->authorize('create', Collection::class);

        $this->validate($request, ['name' => 'required|unique:collections',
            'description' => 'required',
        ]);

        $data = [
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'owner_id' => $request->user()->id,
        ];

        //create a collection using the POST data
        Collection::create($data);

        return redirect()->route('collections.index');
    }

    /**
     * Display a specific collection from a query from the database.
     *
     * @param  int $id
     *      The id of the given collection to be retrieved from the collections table in database
     * @return The view of the chosen collection
     */
    public function show($id)
    {
        //retrieves the collection from DB with given id
        try {
            $collection = Collection::findOrFail($id);
        } catch (ModelNotFoundException $ex) {
            $msg = "Collection not found";
            return view('errors/404', array('message' => $msg));
        }

        //check if user can view collection
        $this->authorize('view', $collection);

        //find all series that belong to the collection
        $series = Series::all()->where('collection_id', $collection->id);

        //array contains a single collection from the DB with all attributes {name, description...}
        //This info will be displayed in view
        return view('collection/view', array('collection'=>$collection, 'series'=>$series));
    }

    /**
     * Show the collection and edit it.
     *
     * @param  int $id
     *      The id of the given collection to be retrieved from the collections table in database
     * @return The edit page with the chosen collection as an arguement
     */
    public function edit($id)
    {
        //retreives the collection from DB with given id
        $collection = Collection::find($id);

        //check if user can update collection
        $this->authorize('update', $collection);

        //array contains a single collection from the DB with all attributes {name, description...}
        //This info will used as placeholders in collection edit form
        return view('/collection/edit', array('collection' => $collection));

    }

    /**
     * Update a specific collection in the DB with information from the collection edit form
     *
     * @param  int $id
     *      The id of the given collection to be retrieved from the collections table in database and edited
     * @return The view page of the given collection with the collection as an argument using the updated information and
     */
    public function update($id, Request $request)
    {
        //find collection
        $collection = Collection::find($id);

        //check if user can update collection
        $this->authorize('update', $collection);

        //If validation passes, code will continue executing normally.
        //However, if validation fails, an  Illuminate\Contracts\Validation\ValidationException will be thrown
        //and is automatically caught and a redirect to the user's previous location.
        $this->validate($request, ['name' => 'required',
            'description' => 'required',
        ]);

        //update existing columns
        $collection->name = Input::get('name');
        $collection->description = Input::get('description');
        $collection->save();

        return redirect()->route('collections.show', ['collection' => $collection]);
    }

    /**
     * Delete a specific collection from the database.
     *
     * @param  int $id
     *      id of collection to remove
     * @return
     *      collections, URL /collections, route(collections.index), calls index() view of all collections
     */
    public function destroy($id)
    {
        //find collection
        $collection = Collection::find($id);

        //check if user can delete collection
        $this->authorize('delete', $collection);

        $collection->delete();

        return redirect()->route('collections.index');
    }

}

resources/views/collection/create.blade.php
@extends('layouts.app')
@section('extracss')
    <link rel="stylesheet" href="/js/pdfjs/web/buttonFormat.css">
@endsection
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">

                    <div class="col-sm-offset-9 col-sm-3">
                        {{--back button--}}
                        {{ Form::open(array('route' => 'collections.index')) }}
                        {{ Form::hidden('_method', 'GET') }}
                        {{ Form::submit('Back', array('class' => 'btn btn-primary')) }}
                        {{ Form::close() }}
                    </div>

                    <div class="col-sm-12 panel-heading">Create a new Collection</div>
                    <div class="col-sm-12 panel-body">

                        {{ Form::open(array('route' => 'collections.store')) }}
                        {{ csrf_field() }}

                        {{ Form::label('name', 'Collection Title') }}
                        {{ Form::text('name', "", ['placeholder' => 'Enter the title']) }}

                        @if ($errors->has('name'))
                            @if ($error = $errors->first('name'))
                                <div class="alert alert-danger">
                                    {{ $error }}
                                </div>
                            @endif
                        @endif

                        <div class="col-sm-12">
                            {{ Form::label('description', 'Collection Description') }}
                        </div>
                        <div class="col-sm-12">
                            {{ Form::textarea('description', "", ['placeholder' => 'Enter the description']) }}
                        </div>
                        @if ($errors->has('description'))
                            @if ($error = $errors->first('description'))
                                <div class="alert alert-danger">
                                    {{ $error }}
                                </div>
                            @endif
                        @endif
                        <div class="col-sm-12">
                            {{ Form::submit('Create', array('class' => 'btn btn-primary')) }}
                            {{ Form::close() }}
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/collection/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-offset-8 col-sm-2">
                {{--back button--}}
                {{ Form::open(array('route' => array('collections.show', $collection->id))) }}
                {{ Form::hidden('_method', 'GET') }}
                {{ Form::submit('Back', array('class' => 'btn btn-primary')) }}
                {{ Form::close() }}
            </div>
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading col-sm-10">Edit Collection</div>

                    <div class="panel-body col-sm-12">


                        {{ Form::open(array('route' => array('collections.update', $collection->id))) }}
                        {{ csrf_field() }}
                        {{ method_field("PUT") }}

                        {{ Form::label('name', 'Collection title') }}
                        {{ Form::text('name', $collection->name) }}
                            <br />
                        {{ Form::label('description', 'Collection description') }}
                        {{ Form::textarea('description', $collection->description) }}

                        <div class="col-sm-offset-6">
                            {{ Form::submit('Update', array('class' => 'btn btn-primary')) }}
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/collection/index.blade.php
@extends('layouts.app')

@section('content')
    <br>
    <div class="container">
        <div class="row justify-content-center">
            <div class="panel panel-default col-sm-12">
                <div class="panel-body">
                    <b>Collections</b>
                    @can('create', App\Collection::class)
                    <!-- The Current User Can Create New Collection -->
                        {{--create collections button--}}
                        <a href="{{  route('collections.create') }}"><button role="button" class="btn btn-primary">Create a Collection</button></a>
                    @endcan
                    <table id="collections" class="table table-striped table-bordered table-hover">
                        <tbody>
                        @foreach($collections as $collection)
                            @can('view', $collection)
                                <tr>
                                    <td>
                                        <a href="{{ route('collections.show', $collection->id) }}">{{$collection->name}}</a>
                                    </td>
                                </tr>
                            @endcan
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/collection/permissions.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading col-sm-10">Manage Permissions</div>
                    <div class="col-sm-2">
                        {{ Form::open(array('route' => array('collections.show', $collection->id))) }}
                        {{ Form::hidden('_method', 'GET') }}
                        {{ Form::submit('Back', array('class' => 'btn btn-primary')) }}
                        {{ Form::close() }}
                    </div>
                    <div class="panel-body">

                        {{ Form::open(array('route' => array('update_permissions', $collection->id))) }}
                        {{ Form::hidden('_method', 'POST') }}

                        <table class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                            <thead>
                            <tr>

                                <th>Firstname</th>
                                <th>Lastname</th>
                                <th>E-mail</th>
                                <th>Create series</th>
                                <th>Full view</th>
                                <th>Anonymised view</th>
                                <th>Update collection</th>
                                <th>Delete collection</th>
                                <th>Allow Management Of Permissions</th>

                            </tr>
                            </thead>

                            <tbody>

                            @foreach($users as $user)
                                <tr>
                                    <td>
                                        {{ $user->firstname }}
                                    </td>
                                    <td>
                                        {{ $user->lastname }}
                                    </td>
                                    <td>
                                        {{ $user->email }}
                                    </td>
                                    <td>
                                        <input name="create[]" type="checkbox" value='{{$user->id}}'
                                           @foreach($permissions as $permission)
                                                @if ($permission->owner_id == $user->id
                                                    && $permission->permissions == 'create')
                                                        checked='true'
                                                @endif
                                            @endforeach
                                        >
                                    </td>
                                    <td>
                                        <input name="view[]" type="checkbox" value='{{$user->id}}'
                                           @foreach($permissions as $permission)
                                               @if ($permission->owner_id == $user->id
                                                   && $permission->permissions == 'view')
                                                        checked='true'
                                                @endif
                                            @endforeach
                                        >
                                    </td>
                                    <td>
                                        <input name="anonymised[]" type="checkbox" value='{{$user->id}}'
                                           @foreach($permissions as $permission)
                                               @if ($permission->owner_id == $user->id
                                                   && $permission->permissions == 'anonymised')
                                                        checked='true'
                                                @endif
                                            @endforeach
                                        >
                                    </td>
                                    <td>
                                        <input name="update[]" type="checkbox" value='{{$user->id}}'
                                           @foreach($permissions as $permission)
                                               @if ($permission->owner_id == $user->id
                                                    && $permission->permissions == 'update')
                                                        checked='true'
                                                @endif
                                            @endforeach
                                        >
                                    </td>
                                    <td>
                                        <input name="delete[]" type="checkbox" value='{{$user->id}}'
                                           @foreach($permissions as $permission)
                                               @if ($permission->owner_id == $user->id
                                                    && $permission->permissions == 'delete')
                                                        checked='true'
                                                @endif
                                            @endforeach
                                        >
                                    </td>
                                    <td>
                                        <input name="manage[]" type="checkbox" value='{{$user->id}}'
                                               @foreach($permissions as $permission)
                                               @if ($permission->owner_id == $user->id
                                                    && $permission->permissions == 'manage')
                                               checked='true'
                                                @endif
                                                @endforeach
                                        >
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                        <div class="col-sm-2 col-sm-offset-10">

                            {{ Form::submit('Apply', array('class' => 'btn btn-primary')) }}
                            {{ Form::close() }}

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/collection/view.blade.php
@extends('layouts.app')
@section('extracss')
    <link rel="stylesheet" href="/js/pdfjs/web/buttonFormat.css">
@endsection
@section('content')
    <section class="section-60 section-sm-100">
        <div class="shell text-center text-md-center">
            <div class="range range-md-middle range-md-center">
                <div class="col-sm-offset-4 col-sm-2">
                @can('createSeries', $collection)
                    <!-- The Current User Can Create New Series -->
                        {{--create button--}}
                        {{ Form::open(array('route' => array('series-create', $collection->id ))) }}
                        {{ Form::hidden('_method', 'GET') }}
                        {{ Form::submit('Create Series', array('class' => 'btn btn-primary')) }}
                        {{ Form::close() }}
                    @endcan
                </div>
                <div class="col-sm-2">
                    @can ('manage', $collection)
                        {{--manage permissions button--}}
                        {{ Form::open(array('route' => array('collection_permission', $collection->id ))) }}
                        {{ Form::hidden('_method', 'GET') }}
                        {{ Form::submit('Manage Permissions', array('class' => 'btn btn-primary')) }}
                        {{ Form::close() }}
                    @endcan
                </div>

            </div>
        </div>
    </section>

    <div class="row">
        <div class="col-sm-8 col-sm-push-2">
            <div class="panel panel-default">

                <div class="panel-heading">
                    <h3 class="panel-heading">{{$collection->name}}</h3>
                </div>

                <div class="panel-body content">
                    <p><strong>Description:</strong></p>
                    {!! $collection->description !!}
                </div>

                {{--table for series--}}
                <table class="table table-bordered table-hover table-striped">
                    <tbody>



                    @foreach($series as $series)
                        @can('view', $series)
                            <tr>
                                <td>
                                    <a href="{{ route('series.show', $series->id) }}"/>{{ $series->name }}
                                </td>
                            </tr>
                        @endcan
                    @endforeach
                    </tbody>
                </table>

            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-3">
                @can('update', $collection)
                    <!-- The Current User Can edit The collection -->
                        {{--edit button--}}
                        {{ Form::open(array('route' => array('collections.edit', $collection))) }}
                        {{ Form::hidden('_method', 'GET') }}
                        {{ Form::submit('Edit collection', array('class' => 'btn btn-primary')) }}
                        {{ Form::close() }}
                    @endcan
                </div>
                <div class="col-sm-3">
                    @can('delete', $collection)
                        {{--delete button--}}
                        {{ Form::open(array('route' => array('collections.destroy', $collection))) }}
                        {{ Form::hidden('_method', 'DELETE') }}
                        {{ Form::submit('Delete collection', array('class' => 'btn btn-primary')) }}
                        {{ Form::close() }}
                    @endcan
                </div>
                <div class="col-sm-3">
                    {{--back button--}}
                    {{ Form::open(array('route' => 'collections.index')) }}
                    {{ Form::hidden('_method', 'GET') }}
                    {{ Form::submit('Back', array('class' => 'btn btn-primary')) }}
                    {{ Form::close() }}
                </div>
            </div>


        </div>
    </div>

@endsection